version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1880:1883"
      - "8883:8883"
      - "8888:8888"
    volumes:
      - ./mosquitto/conf.d:/mosquitto/config/conf.d
      - ./mosquitto/log:/mosquitto/log
      - ./mosquitto/data:/mosquitto/data
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - TZ=UTC
      - ALLOW_ANONYMOUS=true
      - CERTFILE=/etc/letsencrypt/live/example.com/cert.pem
      - CAFILE=/etc/letsencrypt/live/example.com/chain.pem
      - KEYFILE=/etc/letsencrypt/live/example.com/privkey.pem
    command: mosquitto -c /mosquitto/config/mosquitto.conf
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-h", "127.0.0.1", "-t", "$SYS/#", "-C", "1"]
      interval: 10s
      timeout: 5s
      retries: 3
