version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - 7887:1883
      - 9009:9001
    volumes: 
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    environment:
      - VIRTUAL_HOST=xxx.xxx.xxx
      - LETSENCRYPT_HOST=xxx.xxx.xxx
      - LETSENCRYPT_EMAIL=xxx@gmail.com

volumes:
  mosquitto_data:
  mosquitto_log:

networks:
  default:
    external:
      name: nginxproxy_default